#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartUserControl, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    ,               sensorAnalog)
#pragma config(Sensor, dgtl1,  ,               sensorDigitalOut)
#pragma config(Sensor, dgtl2,  ,               sensorDigitalOut)
#pragma config(Sensor, dgtl3,  ,               sensorDigitalOut)
#pragma config(Sensor, dgtl4,  ,               sensorDigitalOut)
#pragma config(Sensor, dgtl10, ,               sensorDigitalOut)
#pragma config(Sensor, dgtl11, ,               sensorDigitalOut)
#pragma config(Sensor, dgtl12, ,               sensorDigitalOut)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(125)

#include "Vex_Competition_Includes.c"

//FL = 2 FR = 3
//BL = 1 BR = 10

int spinnerspeed = 0;
int maxspinnerspeed = 60;
int spinnermultiplier = 16;
bool intakeactive = false;
int LEDCount = 0;
bool LEDActive = false;

void go(int v0, int v1, int v2, int v3) {
	motor[port1] = v0;
	motor[port2] = v1;
	motor[port3] = v2;
	motor[port10] = v3;
}

int fix(int inp, int max) {
	if (inp > max) {
		inp = max;
	} else if (inp < -max) {
		inp = -max;
	}
	return inp;
}

int fix(int inp) {
	return fix(inp, 127);
}

int deWine(int inp){
	inp = fix(inp);
	if((inp < 20) && (inp > -20)) {
		return 0;
	}
	return inp;
}

void spinnerIncrease() {
	spinnerspeed = fix(spinnerspeed + 1, maxspinnerspeed * spinnermultiplier);
}

void spinnerDecrease() {
	spinnerspeed = fix(spinnerspeed - 1, maxspinnerspeed * spinnermultiplier);
}

void doSpinners() {


		// Send to motors
		motor[port4] = floor(spinnerspeed / spinnermultiplier);
		motor[port5] = floor(spinnerspeed / spinnermultiplier);
		motor[port6] = floor(spinnerspeed / spinnermultiplier);
		motor[port7] = floor(spinnerspeed / spinnermultiplier);
}

void pre_auton() {
	bStopTasksBetweenModes = true;
}

task autonomous() {
	go(127, 127, 127, 127);
	wait1Msec(2000);
	go(0, 0, 0, 0);
}

task usercontrol() {
	SensorValue[dgtl1] = true;
	SensorValue[dgtl2] = true;
	SensorValue[dgtl3] = true;
	SensorValue[dgtl4] = true;
	SensorValue[dgtl11] = true;
	SensorValue[dgtl12] = true;
	while(true){
		//updateLCD();

		// Update LEDs
		LEDCount++;
		if (LEDCount > 200) {
			LEDCount = 0;
		}

		if (LEDCount >= 100) LEDActive = true;
		else LEDActive = false;

		if (nImmediateBatteryLevel == 0) SensorValue[dgtl1] = false;
		else SensorValue[dgtl1] = LEDActive;

		if (SensorValue[in1] == 0) SensorValue[dgtl2] = false;
		else SensorValue[dgtl2] = LEDActive;

		if (BackupBatteryLevel == 0) SensorValue[dgtl3] = false;
		else SensorValue[dgtl3] = LEDActive;

		// Wheels
		motor[port1] = deWine(vexRT[Ch3]);
		motor[port2] = deWine(vexRT[Ch3]);
		motor[port3] = deWine(vexRT[Ch2]);
		motor[port10] = deWine(vexRT[Ch2]);

		// Belt
		if (vexRT[Btn5U]) {
			motor[port8] = 127;
		} else if (vexRT[Btn5D]) {
			motor[port8] = -127;
		} else {
			motor[port8] = 0;
		}

		// Intake
		if (vexRT[Btn7D]) {
			intakeactive = true;
		} else if (vexRT[Btn7L]) {
			intakeactive = false;
		}

		if (intakeactive) motor[port9] = 127;
		else motor[port9] = 0;

		// Get max spinner speed
		if (vexRT[Btn8D]) maxspinnerspeed++;
		else if (vexRT[Btn8R]) maxspinnerspeed = 60;

		if (maxspinnerspeed > 127) maxspinnerspeed = 127;

		// Calculate Spinner
		if (vexRT[Btn6U]) {
			spinnerIncrease();
		} else {
			maxspinnerspeed = 60;
			if (spinnerspeed > 0) {
				spinnerDecrease();
			} else if(spinnerspeed < 0) {
				spinnerIncrease();
			} else {
				spinnerspeed = 0;
			}
		}

		// Emergency stop
		if (vexRT[Btn8L]) {
			spinnerspeed = 0;
		}

		doSpinners();
	}
}
